### ISSUE TITLE
Install 24.7.1(x64) on windows10/11 encounter: Failed to run pre_install

### ISSUE THREAD

**Issue by sandpioneer** [conda-forge/miniforge#641] opened 2024-09-10 02:09 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Install 24.7.1(x64) on windows10/11 encounter: Failed to run pre_install
![Snipaste_2024-09-10_09-08-26](https://github.com/user-attachments/assets/d5da22d7-6f77-4146-bdd4-fd00cd1cf105)

### Installed packages

```shell
install error
```

### Environment info

```shell
24.7.1
```

**Comment by hmaarrfk** [comment] 2024-09-10 02:28
Hmm i suspect it has to do with: https://github.com/conda-forge/miniforge/blob/main/Miniforge3/mambaforge_deprecation.bat


I suggest you use `Miniforge3.exe` while we resolve this issue. 

I might delay 24.7.1-1 since that one has the brownouts and my intention is to have 1 (working) verison with warnings without brownouts.

**Comment by jaimergp** [comment] 2024-09-10 07:29
Can you click on "Ignore" and right click on the text details under the progress bar, choose "Copy to clipboard" and paste the result here? I see some syntax errors behind the alert 🤔

**Comment by hmaarrfk** [comment] 2024-09-15 23:47
![IMG_0524](https://github.com/user-attachments/assets/91ea764c-e37f-4606-b35e-26782086b7e8)

**Comment by hmaarrfk** [comment] 2024-09-15 23:48
The nice thing is that you can "press ignore" and it will work....

**Comment by marcoesters** [comment] 2024-09-16 14:07
The problem is that the `else` part of the statement is in a new line. It must be in the same line as the closing parenthesis.

You will also run into the issue that `msg` is not available on all Windows versions (I think home editions don't have it).

**Comment by hmaarrfk** [comment] 2024-09-16 14:39
hmm thank you for the notes we can likely fix the `else` part. not sure about the `msg` command.

Because you can "ignore" it, i'm somewhat even tempted to "ignore this" as a fading problem..... but isuruf reminded me that I shouldn't be so quick to ignore problems... though I really don't know what to do.....

**Comment by jaimergp** [comment] 2024-09-17 21:04
I can sketch a solution, sorry about the breakage. We don't really need to use `msg`.

**Comment by jaimergp** [comment] 2024-09-19 07:37
Added https://github.com/conda-forge/miniforge/pull/647

**Closed** 2024-09-22 15:34 UTC
Labels: bug, windows

**Comment by hmaarrfk** [comment] 2024-09-22 15:37
Thank you all. A new release of Mambaforge is coming.

We are in the process of releasing this, however, `Mambaforge` now being deprecated we are hoping this isn't going to be an issue for many users.

**Comment by li-zheng-hao** [comment] 2024-11-20 02:59
same problem in v24.9.2 and Windows 10 Pro

**Comment by hmaarrfk** [comment] 2024-11-20 04:26
Please open a new issue. 

Please use the Miniforge3-Windows installer. 

No PyPy. No Mambaforge.

**Comment by li-zheng-hao** [comment] 2024-11-20 04:39
> Please open a new issue.
> 
> Please use the Miniforge3-Windows installer.
> 
> No PyPy. No Mambaforge.

thanks! 👍
