### ISSUE TITLE
miniforge missing a few CDTS

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#37] opened 2020-06-21 01:53 UTC
I'm trying to use miniforge as my daily driver to see what random issues arise.

It seems we are dependending on a few default CDTs

```
conda.exceptions.ResolvePackageNotFound: 
  - mesa-dri-drivers-cos6-x86_64
  - libxcomposite-devel-cos6-x86_64
  - mesa-libegl-devel-cos6-x86_64
  - libxrender-devel-cos6-x86_64
  - libxrandr-devel-cos6-x86_64
  - libxext-cos6-x86_64
  - libsm-devel-cos6-x86_64
  - libxext-devel-cos6-x86_64
  - libxinerama-devel-cos6-x86_64
  - libxcursor-devel-cos6-x86_64
  - libx11-devel-cos6-x86_64
  - libxdamage-cos6-x86_64
  - xorg-x11-proto-devel-cos6-x86_64
  - libxtst-devel-cos6-x86_64
  - libxdamage-devel-cos6-x86_64
  - libxxf86vm-cos6-x86_64
  - libselinux-cos6-x86_64
  - libxi-devel-cos6-x86_64
  - mesa-libgl-devel-cos6-x86_64
  - libxfixes-devel-cos6-x86_64
  - libice-devel-cos6-x86_64


```

We should probably rebuild them if we want to fully remove the dependency on default

**Comment by isuruf** [comment] 2020-06-21 01:56
Duplicate of https://github.com/conda-forge/conda-forge.github.io/issues/1085

**Closed by isuruf** 2020-06-21 01:56 UTC
