### ISSUE TITLE
Support request for pypy3 macOS arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by zhouyc98** [conda-forge/miniforge#398] opened 2022-12-29 06:04 UTC
### Comment:

Hi,
I noticed that pypy3 has released v7.3.10 which supports macOS arm64 (https://www.pypy.org/download.html). 
I wonder when will miniforge support it?
Thanks in advance.

**Comment by isuruf** [comment] 2022-12-30 13:06
Duplicate of https://github.com/conda-forge/pypy3.6-feedstock/issues/88

**Closed by isuruf** 2022-12-30 13:06 UTC
Labels: question
