### ISSUE TITLE
mambaforge not using rc file 

### ISSUE THREAD

**Issue by codecypher** [conda-forge/miniforge#287] opened 2022-04-05 00:21 UTC
### Comment:

It seems that mamba is not using settings in ~/.condarc or ~/.mambarc on macOS?

I have installed mambaforge using brew in /usr/local/Caskroom/mambaforge/base.

Thanks

**Comment by hmaarrfk** [comment] 2022-04-05 00:40
I'm not sure we really support "Brew" installation of conda forge.

Conda-forge is pretty standalone. I really would suggest just using the instructions we provide.

https://github.com/conda-forge/miniforge#unix-like-platforms

Otherwise, maybe try to report the issues to Homebrew???

**Comment by codecypher** [comment] 2022-04-05 00:54
Okay uninstalled and installed and mamba still does not seem to be using .condarc or .mambarc settings

**Comment by hmaarrfk** [comment] 2022-04-05 01:01
I'm not sure where `no_banner` is documented as a mamba feature.

I see the flags and the environment variables, but no config files
https://github.com/mamba-org/mamba/commit/822ee4b9aa9f1e335a3896daeab1f236a73fcd3a

**Comment by codecypher** [comment] 2022-04-05 01:02
Doesn't really matter, doesn't seem to be using rc file.

**Comment by hmaarrfk** [comment] 2022-04-05 01:24
:/ I'm going to take your tone to be friendly.

The thing is, that I use mamba and conda every day, on multiple computers, accross multiple versions. We use custom channels and thus if the config file was completely being ignored, as you suggested in your orginal post.

my hunch is that this a bug due to a specific feature mamba has implemented that does not exist in conda. i searched for the documentation for no-banner, and I didn't find much.

in fact, the code path that shows the `--no-banner` PR doesn't doesn't really allude to the rc file. The raised issue in Mamba that the PR closes also doesn't make any mention of the new configuration option. They do suggest setting an environment specific environment variable.

Because you kindly obliged to re-install i'm inclined to say that it is a mamba issue, not specifically related mambaforge. You likely have a case to open an issue directly with mamba. We only aggregate mamba and conda into an installer.

PS. We do ask kindly that people provide us with detailed version information of their installation. You decided to ignore that request.

I've been spending some time to find if mamba can print its config, it seems that there is no implementation of the equivalent of `conda config --show`.

However, you can try:
```
mamba search A_PACKAGE_YOU_HAVE_IN_YOUR_CHANNEL
```

and it should list it if it is in your `.condarc` file.

As a test, I searched for

```
mamba search opencv
```
and it lists packages from conda-forge
```
$ mamba search opencv

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Loading channels: done
# Name                       Version           Build  Channel
opencv                        2.4.12     np110py27_0  conda-forge
opencv                        2.4.12     np110py27_1  conda-forge
opencv                        2.4.12     np110py27_2  conda-forge
opencv                        2.4.12     np111py27_0  conda-forge
[...]
```

When removing my `${HOME}/.condarc`, and `${HOME}/mambaforge/.condarc` I get

```
$ mamba search opencv

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Loading channels: done
# Name                       Version           Build  Channel
opencv                         3.3.1  py27h17fce66_0  pkgs/main
opencv                         3.3.1  py27h61133dd_2  pkgs/main
opencv                         3.3.1  py27h6cbbc71_1  pkgs/main
opencv                         3.3.1  py27h9248ab4_2  pkgs/main
opencv                         3.3.1  py27h9bb06ff_1  pkgs/main
opencv                         3.3.1  py27hdcf4849_0  pkgs/main
opencv                         3.3.1  py35h0b7da17_0  pkgs/main
opencv                         3.3.1  py35h61133dd_2  pkgs/main
opencv                         3.3.1  py35h6cbbc71_1  pkgs/main
opencv                         3.3.1  py35h9248ab4_2  pkgs/main
opencv                         3.3.1  py35h9bb06ff_1  pkgs/main
opencv                         3.3.1  py35hb7523de_0  pkgs/main
opencv                         3.3.1  py36h0a11808_0  pkgs/main
opencv                         3.3.1  py36h0f6f1c3_0  pkgs/main
opencv                         3.3.1  py36h61133dd_2  pkgs/main
opencv                         3.3.1  py36h6cbbc71_1  pkgs/main
opencv                         3.3.1  py36h9248ab4_2  pkgs/main
opencv                         3.3.1  py36h9bb06ff_1  pkgs/main
opencv                         3.4.1  py27h40b0b35_1  pkgs/main
opencv                         3.4.1  py27h40b0b35_2  pkgs/main
opencv                         3.4.1  py27h40b0b35_3  pkgs/main
opencv                         3.4.1  py27h6fd60c2_1  pkgs/main
opencv                         3.4.1  py27h6fd60c2_2  pkgs/main
opencv                         3.4.1  py27h6fd60c2_3  pkgs/main
opencv                         3.4.1  py35h40b0b35_1  pkgs/main
opencv                         3.4.1  py35h40b0b35_2  pkgs/main
opencv                         3.4.1  py35h6fd60c2_1  pkgs/main
opencv                         3.4.1  py35h6fd60c2_2  pkgs/main
opencv                         3.4.1  py36h40b0b35_1  pkgs/main
opencv                         3.4.1  py36h40b0b35_2  pkgs/main
opencv                         3.4.1  py36h40b0b35_3  pkgs/main
opencv                         3.4.1  py36h6fd60c2_1  pkgs/main
opencv                         3.4.1  py36h6fd60c2_2  pkgs/main
opencv                         3.4.1  py36h6fd60c2_3  pkgs/main
opencv                         3.4.1  py37h40b0b35_3  pkgs/main
opencv                         3.4.1  py37h6fd60c2_3  pkgs/main
opencv                         3.4.2  py27h40b0b35_0  pkgs/main
opencv                         3.4.2  py27h40b0b35_1  pkgs/main
opencv                         3.4.2  py27h6fd60c2_0  pkgs/main
opencv                         3.4.2  py27h6fd60c2_1  pkgs/main
opencv                         3.4.2  py35h40b0b35_0  pkgs/main
opencv                         3.4.2  py35h40b0b35_1  pkgs/main
opencv                         3.4.2  py35h6fd60c2_0  pkgs/main
opencv                         3.4.2  py35h6fd60c2_1  pkgs/main
opencv                         3.4.2  py36h40b0b35_0  pkgs/main
opencv                         3.4.2  py36h40b0b35_1  pkgs/main
opencv                         3.4.2  py36h6fd60c2_0  pkgs/main
opencv                         3.4.2  py36h6fd60c2_1  pkgs/main
opencv                         3.4.2  py37h40b0b35_0  pkgs/main
opencv                         3.4.2  py37h40b0b35_1  pkgs/main
opencv                         3.4.2  py37h6fd60c2_0  pkgs/main
opencv                         3.4.2  py37h6fd60c2_1  pkgs/main
opencv                         4.5.4 py310h15b3d91_1  pkgs/main
opencv                         4.5.4 py310h3dbb160_2  pkgs/main
opencv                         4.5.4 py310h3dbb160_3  pkgs/main
opencv                         4.5.4  py37h7f95952_1  pkgs/main
opencv                         4.5.4  py37hbeebcbe_2  pkgs/main
opencv                         4.5.4  py37hbeebcbe_3  pkgs/main
opencv                         4.5.4  py38h7f95952_1  pkgs/main
opencv                         4.5.4  py38hbeebcbe_2  pkgs/main
opencv                         4.5.4  py38hbeebcbe_3  pkgs/main
opencv                         4.5.4  py39h7f95952_1  pkgs/main
opencv                         4.5.4  py39hbeebcbe_2  pkgs/main
opencv                         4.5.4  py39hbeebcbe_3  pkgs/main
```

**Comment by codecypher** [comment] 2022-04-05 01:50
Okay thx. My main point was that if I try some of the mamba settings as shown in the documentation using rc file, it does not seem to be using it. The mamba docs say that you can set any setting via env or rc file. As far as I can tell mambaforge is not using the settings.

**Comment by hmaarrfk** [comment] 2022-04-05 02:00
> Obviously, I am using the latest version of mambaforge

This really isn't obvious. conda-forge is a fast moving "rolling release" channel. The lastest release is a moving target.

It really is much faster for you to resolve your issue if you can provide some code that shows your issue. 

This isn't always possible, but it does make the most use of other people's time that you have.

While wolfv does monitor this. I think you will get your answer faster if you can show what settings are being missed by mamba, and submit more complete info regarding your bug directly to https://github.com/mamba-org/mamba

**Comment by hmaarrfk** [comment] 2022-04-05 02:01
I forgot to mention: I'm closing since it seems that only a specific setting is being missed. but the file as a whole is being picked up.

**Comment by codecypher** [comment] 2022-04-05 02:03
Nope I tried several settings and none of them are being picked up. Thanks for nothing.

**Comment by hmaarrfk** [comment] 2022-04-05 02:23
I'm happy to reopen, but I simply can't recreate.

I'm humbly asking if you can provide me with reproducible commands I can run on my machine :/

> As you can see the miniforge page says you can install via brew on macOS which is usually the best way to install linux utils on macOS.

I'm not saying it is a bad tool, but generally stacking tools leads to integration challenges.

I'm sorry if you lost your environments. Typically, commenting out a few lines in your bashrc / zshrc file makes it appear as "conda" is "uninstalled" and lets you try new configs. I will try to remember to offer it as an option to others I reply to.

At this stage, I really am not able to recreate your issues. As such, I am simply unable to help further.

I'll leave this open for others to pass by and attempt to help from the information contained in this issue.

**Comment by codecypher** [comment] 2022-04-05 02:25
It's okay Just a little miffed since I have spent so much time trying to do what you recommended.

FYI This is how you view the .condarc settings.
```bash
conda config --get
```

**Comment by hmaarrfk** [comment] 2022-04-05 02:32
> It seems that the mamba specific settings are being ignored.

This is an issue best raised with mamba-org/mamba 

I am sure you will get a response. Ping me there if you don't.

Please cross reference here so that others may find the issue.

**Comment by codecypher** [comment] 2022-04-05 02:41
Actually, looks like other people are also confused about the [mamba specific settings](https://github.com/mamba-org/mamba/issues/984) not being used (need for separate .mambarc or similar file)

**Comment by hmaarrfk** [comment] 2022-04-05 02:55
Good find. That issue seems dormant.

Maybe you can express your renewed interest? I think `.mambarc` is new and it might be accepted there.

Seeing as we found the upstream issue, is it ok for me to close this one?

**Comment by codecypher** [comment] 2022-04-05 03:03
Sure. Thx.

 I gave thumbs up on the comments. Is there another way to show interest on GitHub issues?

On Apr 4, 2022, at 10:55 PM, Mark Harfouche ***@***.***> wrote:

﻿
Good find. That issue seems dormant.

Maybe you can express your renewed interest? I think .mambarc is new and it might be accepted there.

Seeing as we found the upstream issue, is it ok for me to close this one?

**Comment by hmaarrfk** [comment] 2022-04-05 03:09
I personally don't get notifications from reactions. To me they are a silent way to show support.

I think it is appropriate for you to share your usecase/story.

**Closed by hmaarrfk** 2022-04-05 03:09 UTC
Labels: question
