### ISSUE TITLE
mamba commands not working as expected

### ISSUE THREAD

**Issue by stnatter** [conda-forge/miniforge#497] opened 2023-10-04 05:08 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

mamba clean --a
mamba update --a

result in the following error , while <conda> command has the expected behaviour.
Apple M2 Max, macOS 14.0 (23A344)

```
(base) steffen@snmb ~ % mamba clean --all
argument COMMAND: conflicting subparser: repoquery

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/steffen/miniforge3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/steffen/miniforge3/lib/python3.11/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/Users/steffen/miniforge3/lib/python3.11/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/steffen/miniforge3/lib/python3.11/site-packages/mamba/mamba.py", line 877, in _wrapped_main
        configure_parser_repoquery(p._subparsers._group_actions[0])
      File "/Users/steffen/miniforge3/lib/python3.11/site-packages/mamba/mamba.py", line 805, in configure_parser_repoquery
        p = sub_parsers.add_parser(
            ^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/steffen/miniforge3/lib/python3.11/argparse.py", line 1192, in add_parser
        raise ArgumentError(self, _('conflicting subparser: %s') % name)
    argparse.ArgumentError: argument COMMAND: conflicting subparser: repoquery

`$ /Users/steffen/miniforge3/bin/mamba clean --all`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/steffen/miniforge3/bin/conda
             CONDA_PREFIX=/Users/steffen/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/steffen/miniforge3/bin/python
               CONDA_ROOT=/Users/steffen/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/steffen/miniforge3/bin:/Users/steffen/miniforge3/condabin:/opt/
                          homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/u
                          sr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.crypt
                          exd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.c
                          ryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cry
                          ptexd/codex.system/bootstrap/usr/appleinternal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/steffen/miniforge3
            shell level : 1
       user config file : /Users/steffen/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.6.final.0
       virtual packages : __archspec=1=arm64
                          __osx=14.0=0
                          __unix=0=0
       base environment : /Users/steffen/miniforge3  (writable)
      conda av data dir : /Users/steffen/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/steffen/miniforge3/pkgs
                          /Users/steffen/.conda/pkgs
       envs directories : /Users/steffen/miniforge3/envs
                          /Users/steffen/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.6 Darwin/23.0.0 OSX/14.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

### Installed packages

```shell
# packages in environment at /Users/steffen/miniforge3:
#
# Name                    Version                   Build  Channel
aiocache                  0.12.2             pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.5           py311heffc1b2_0    conda-forge
aiomcache                 0.8.1                    pypi_0    pypi
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alpha_vantage             2.3.1              pyhd8ed1ab_0    conda-forge
anyio                     4.0.0              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311heffc1b2_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.0              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.7.4                h2ed40ff_1    conda-forge
aws-c-cal                 0.6.2                h12c43c8_2    conda-forge
aws-c-common              0.9.3                hb547adb_0    conda-forge
aws-c-compression         0.2.17               h12c43c8_3    conda-forge
aws-c-event-stream        0.3.2                h88fe898_1    conda-forge
aws-c-http                0.7.13               he062130_1    conda-forge
aws-c-io                  0.13.32              h13ba428_4    conda-forge
aws-c-mqtt                0.9.6                h3ffe4bb_2    conda-forge
aws-c-s3                  0.3.17               hf064be9_3    conda-forge
aws-c-sdkutils            0.1.12               h12c43c8_2    conda-forge
aws-checksums             0.1.17               h12c43c8_2    conda-forge
aws-crt-cpp               0.23.1               h96fc18d_5    conda-forge
aws-sdk-cpp               1.11.156             he831950_3    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
bokeh                     3.2.2              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boost-cpp                 1.82.0               hca5e981_5    conda-forge
bottleneck                1.3.7           py311hb49d859_1    conda-forge
brotli                    1.1.0                hb547adb_1    conda-forge
brotli-bin                1.1.0                hb547adb_1    conda-forge
brotli-python             1.1.0           py311ha891d26_1    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311h4a08483_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
conda                     23.7.4          py311h267d04e_0    conda-forge
conda-libmamba-solver     23.9.1             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
confuse                   2.0.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1           py311he4fd1f5_1    conda-forge
cryptography              41.0.4          py311h5fb2c35_0    conda-forge
cvxpy                     1.3.2           py311ha1ab1f8_0    conda-forge
cvxpy-base                1.3.2           py311h9e438b8_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    3.0.2           py311ha891d26_2    conda-forge
cytoolz                   0.12.2          py311heffc1b2_1    conda-forge
dask                      2023.9.3           pyhd8ed1ab_0    conda-forge
dask-core                 2023.9.3           pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0           py311ha891d26_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
distex                    0.7.2                    pypi_0    pypi
distributed               2023.9.3           pyhd8ed1ab_0    conda-forge
ecos                      2.0.11          py311h4add359_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
eventkit                  1.0.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fmt                       10.1.1               h1995070_0    conda-forge
fonttools                 4.43.0          py311heffc1b2_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
frozenlist                1.4.0           py311heffc1b2_1    conda-forge
fsspec                    2023.9.2           pyh1a96a4e_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
hdf5                      1.14.2          nompi_h3aba7b3_100    conda-forge
ib-insync                 0.9.82             pyhd8ed1ab_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
ipykernel                 6.25.2             pyh1050b4e_0    conda-forge
ipython                   8.16.1             pyh31c8845_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py311h267d04e_3    conda-forge
jsonschema                4.19.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.19.1             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.2           py311h267d04e_0    conda-forge
jupyter_events            0.7.0              pyhd8ed1ab_2    conda-forge
jupyter_server            2.7.3              pyhd8ed1ab_1    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5           py311he4fd1f5_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
lcms2                     2.15                 hf2736f0_3    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230802.1      cxx17_h13dd4ca_0    conda-forge
libaec                    1.1.1                h13dd4ca_0    conda-forge
libarchive                3.7.2                h82b9b87_0    conda-forge
libarrow                  13.0.0           h0c25ffe_5_cpu    conda-forge
libblas                   3.9.0           18_osxarm64_openblas    conda-forge
libboost                  1.82.0               h72cdd8a_5    conda-forge
libboost-devel            1.82.0               hf450f58_5    conda-forge
libboost-headers          1.82.0               hce30654_5    conda-forge
libbrotlicommon           1.1.0                hb547adb_1    conda-forge
libbrotlidec              1.1.0                hb547adb_1    conda-forge
libbrotlienc              1.1.0                hb547adb_1    conda-forge
libcblas                  3.9.0           18_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.3.0                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.19                 hb547adb_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.12               h2757513_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libgoogle-cloud           2.12.0               hde42cda_2    conda-forge
libgrpc                   1.57.0               hdbe17d8_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           18_osxarm64_openblas    conda-forge
libmamba                  1.5.1                hace0f30_1    conda-forge
libmambapy                1.5.1           py311h7cacacc_1    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.24          openmp_hd76b1f2_0    conda-forge
libosqp                   0.6.3                h13dd4ca_0    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libprotobuf               4.23.4               hf590ac1_6    conda-forge
libqdldl                  0.1.5                hb7217d7_1    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsolv                   0.7.25               ha614eb4_0    conda-forge
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.19.0               h026a170_1    conda-forge
libtiff                   4.6.0                ha8a6c65_2    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libuv                     1.46.0               hb547adb_0    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.5               h25269f3_1    conda-forge
libzip                    1.10.1               ha0bc3c6_3    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
llvmlite                  0.41.0                  py311_0    numba
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2           py311h0c6baac_1    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
mamba                     1.5.1           py311hb045da1_1    conda-forge
markupsafe                2.1.3           py311heffc1b2_1    conda-forge
matplotlib                3.8.0           py311ha1ab1f8_1    conda-forge
matplotlib-base           3.8.0           py311h3bc9839_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.6           py311he4fd1f5_0    conda-forge
multidict                 6.0.4           py311he2be06e_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.8.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
notebook                  7.0.4              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numba                     0.58.0          np1.22py3.11h8833779_g54c0cf862_0    numba
numexpr                   2.8.7           py311h9e438b8_2    conda-forge
numpy                     1.25.2          py311hb8f3215_0    conda-forge
openjpeg                  2.5.0                h4c1507b_3    conda-forge
openssl                   3.1.3                h53f4e23_0    conda-forge
orc                       1.9.0                hbfdecac_2    conda-forge
osqp                      0.6.3           py311h9e438b8_1    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.1           py311h9e438b8_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.1          py311h8dc27b9_2    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py311heffc1b2_1    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-lets-be-rational       1.0.1                    pypi_0    pypi
py-vollib                 1.0.1                    pypi_0    pypi
pyarrow                   13.0.0          py311hd7bc329_5_cpu    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py311heffc1b2_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyobjc-core               10.0            py311hb702dc4_0    conda-forge
pyobjc-framework-cocoa    10.0            py311hb702dc4_1    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.6          h47c9636_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.18.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytrade                   1.0.0                     dev_0    <develop>
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311heffc1b2_1    conda-forge
pyzmq                     25.1.1          py311hb1af645_1    conda-forge
qdldl-python              0.1.5.post2     py311h4eec4a9_0    conda-forge
quandl                    3.7.0                    pypi_0    pypi
re2                       2023.03.02           hc5e2d97_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.30.2             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4.post0         hb547adb_0    conda-forge
reproc-cpp                14.2.4.post0         h13dd4ca_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.10.3          py311h0563b04_1    conda-forge
ruamel.yaml               0.17.33         py311heffc1b2_1    conda-forge
ruamel.yaml.clib          0.2.7           py311heffc1b2_2    conda-forge
scikit-learn              1.3.1           py311hf0b18b8_0    conda-forge
scipy                     1.11.3          py311h93d07a4_0    conda-forge
scs                       3.2.3           py311h0dc035f_0    conda-forge
seaborn                   0.13.0               hd8ed1ab_0    conda-forge
seaborn-base              0.13.0             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
simplejson                3.19.1          py311heffc1b2_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0          py311hb49d859_1    conda-forge
tblib                     2.0.0              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hb31c410_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py311heffc1b2_1    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.11.2             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ujson                     5.8.0           py311ha891d26_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.5              pyhd8ed1ab_0    conda-forge
uvloop                    0.17.0          py311heffc1b2_2    conda-forge
wcwidth                   0.2.8              pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.6.3              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2023.7.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yaml-cpp                  0.8.0                h13dd4ca_0    conda-forge
yarl                      1.9.2           py311heffc1b2_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstandard                 0.21.0          py311hae4035a_1    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /Users/steffen/miniforge3
            shell level : 1
       user config file : /Users/steffen/.condarc
 populated config files : /Users/steffen/miniforge3/.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.6.final.0
       virtual packages : __archspec=1=arm64
                          __osx=14.0=0
                          __unix=0=0
       base environment : /Users/steffen/miniforge3  (writable)
      conda av data dir : /Users/steffen/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/steffen/miniforge3/pkgs
                          /Users/steffen/.conda/pkgs
       envs directories : /Users/steffen/miniforge3/envs
                          /Users/steffen/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.6 Darwin/23.0.0 OSX/14.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jaimergp** [comment] 2023-10-04 08:26
This is a bug in `mamba` x `conda-libmamba-solver` x Python 3.11, as reported in https://github.com/conda/conda-libmamba-solver/issues/303. Fix submitted at https://github.com/mamba-org/mamba/pull/2878 but a release is still pending.

**Comment by sotosoul** [comment] 2023-10-15 13:31
Until a fix becomes available, what worked for me is to downgrade conda to 23.7.4 and uninstall from base with `conda remove conda-libmamba-solver`.

**Comment by me9hanics** [comment] 2023-11-27 23:35
> This is a bug in `mamba` x `conda-libmamba-solver` x Python 3.11, as reported in [conda/conda-libmamba-solver#303](https://github.com/conda/conda-libmamba-solver/issues/303). Fix submitted at [mamba-org/mamba#2878](https://github.com/mamba-org/mamba/pull/2878) but a release is still pending.

For me, it does this even when trying to install Python 3.10.

**Comment by GinGin520** [comment] 2024-03-27 13:35
I got this problem again! Is this problem solved?

(ldm) [jhe44@cxu22-03 instructgen]$ mamba clean --a
argument COMMAND: conflicting subparser: repoquery

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/p61/jhe44/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/p61/jhe44/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/p61/jhe44/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/p61/jhe44/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 877, in _wrapped_main
        configure_parser_repoquery(p._subparsers._group_actions[0])
      File "/p61/jhe44/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 805, in configure_parser_repoquery
        p = sub_parsers.add_parser(
            ^^^^^^^^^^^^^^^^^^^^^^^
      File "/p61/jhe44/anaconda3/lib/python3.11/argparse.py", line 1192, in add_parser
        raise ArgumentError(self, _('conflicting subparser: %s') % name)
    argparse.ArgumentError: argument COMMAND: conflicting subparser: repoquery

`$ /p61/jhe44/anaconda3/condabin/mamba clean --a`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=ldm
                CONDA_EXE=/p61/jhe44/anaconda3/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/p61/jhe44/anaconda3/envs/ldm
           CONDA_PREFIX_1=/p61/jhe44/anaconda3
    CONDA_PROMPT_MODIFIER=(ldm)
         CONDA_PYTHON_EXE=/p61/jhe44/anaconda3/bin/python
               CONDA_ROOT=/p61/jhe44/anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                  MANPATH=:
               MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefil
                          es:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/home/vax10/u38/jhe44/.vscode-
                          server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/remote-cli:/p6
                          1/jhe44/anaconda3/envs/ldm/bin:/p61/jhe44/anaconda3/condabin:/usr/shar
                          e/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/u/jhe
                          44/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : ldm
    active env location : /p61/jhe44/anaconda3/envs/ldm
            shell level : 2
       user config file : /u/jhe44/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : 24.1.2
         python version : 3.11.8.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.3=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /p61/jhe44/anaconda3  (writable)
      conda av data dir : /p61/jhe44/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /p61/jhe44/anaconda3/pkgs
                          /u/jhe44/.conda/pkgs
       envs directories : /p61/jhe44/anaconda3/envs
                          /u/jhe44/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.8 Linux/4.18.0-539.el8.x86_64 centos/8 glibc/2.28
                UID:GID : 2505:1102
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

(ldm) [jhe44@cxu22-03 instructgen]$

**Comment by hmaarrfk** [comment] 2024-03-27 13:51
edited yoru comment for formatting.

You are using `anaconda3` and anaconda channels.

please contact them for support. You are writing an issue on conda-forge's miniforge installers which is a similar, but unrelated project.

**Comment by hmaarrfk** [comment] 2024-03-27 13:51
Given the original was a bug in mamba and fixed, i'm going to close this to encourage users to open new issues.

**Closed by hmaarrfk** 2024-03-27 13:51 UTC
Labels: bug
