### ISSUE TITLE
Anaconda default channel seems to be added

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#44] opened 2020-08-03 14:58 UTC
Issue:
I'm installing miniforge and it seems that the default anaconda channel is added

Maybe we need to specify: https://github.com/conda/constructor/blob/master/CONSTRUCT.md#conda_default_channels

```
[32;1m$ export PATH=/root/miniforge3/bin:$PATH[0;m
[32;1m$ source /root/miniforge3/etc/profile.d/conda.sh[0;m
[32;1m$ echo "pkgs_dirs:"               >> ~/.condarc[0;m
[32;1m$ echo "  - $CONDA_PKG_CACHE_DIR" >> ~/.condarc[0;m
[32;1m$ conda config --set show_channel_urls true[0;m
[32;1m$ conda config --show[0;m
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: True
bld_path: 
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: flexible
channels:
  - defaults
  - https://conda.anaconda.org/conda-forge
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: /root/miniforge3/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults: 
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local: 
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.7
```
<br/>
Environment (<code>conda list</code>):
<details>

```

## Package Plan ##

  environment location: /root/miniforge3

  added / updated specs:
    - _libgcc_mutex==0.1=conda_forge
    - _openmp_mutex==4.5=0_gnu
    - brotlipy==0.7.0=py37h8f50634_1000
    - bzip2==1.0.8=h516909a_2
    - ca-certificates==2020.6.20=hecda079_0
    - certifi==2020.6.20=py37hc8dfbb8_0
    - cffi==1.14.1=py37h2b28604_0
    - chardet==3.0.4=py37hc8dfbb8_1006
    - conda-package-handling==1.6.0=py37h8f50634_2
    - conda==4.8.3=py37hc8dfbb8_1
    - cryptography==3.0=py37hb09aad4_0
    - idna==2.10=pyh9f0ad1d_0
    - ld_impl_linux-64==2.34=hc38a660_9
    - libffi==3.2.1=he1b5a44_1007
    - libgcc-ng==9.3.0=h24d8f2e_11
    - libgomp==9.3.0=h24d8f2e_11
    - libstdcxx-ng==9.3.0=hdf63c60_11
    - ncurses==6.2=he1b5a44_1
    - openssl==1.1.1g=h516909a_1
    - pip==20.2=py_0
    - pycosat==0.6.3=py37h8f50634_1004
    - pycparser==2.20=pyh9f0ad1d_2
    - pyopenssl==19.1.0=py_1
    - pysocks==1.7.1=py37hc8dfbb8_1
    - python==3.7.8=h6f2ec95_0_cpython
    - python_abi==3.7=1_cp37m
    - readline==8.0=he28a2e2_2
    - requests==2.24.0=pyh9f0ad1d_0
    - ruamel_yaml==0.15.80=py37h8f50634_1001
    - setuptools==49.2.0=py37hc8dfbb8_0
    - six==1.15.0=pyh9f0ad1d_0
    - sqlite==3.32.3=hcee41ef_1
    - tk==8.6.10=hed695b0_0
    - tqdm==4.48.0=pyh9f0ad1d_0
    - urllib3==1.25.10=py_0
    - wheel==0.34.2=py_1
    - xz==5.2.5=h516909a_1
    - yaml==0.2.5=h516909a_0
    - zlib==1.2.11=h516909a_1006
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):

- Ubuntu docker
- Miniforge Latest

**Comment by isuruf** [comment] 2020-08-03 15:05
You probably have another conda environment activated. I checked and the latest installer works as intended.

**Comment by hmaarrfk** [comment] 2020-08-03 16:44
Sorry i guess i had omitted a:

```
conda config --add channels UNREALTEDCHANNELNAME
```
which seems to triggers the addition of the `defaults`.

The reproducing code is
```
docker run -it ubuntu /bin/bash
```
```
apt-get update
apt-get install wget -y
wget https://github.com/conda-forge/miniforge/releases/download/4.8.3-5/Miniforge3-4.8.3-5-Linux-x86_64.sh
bash Miniforge3-4.8.3-5-Linux-x86_64.sh -b
source /root/miniforge3/bin/activate
conda config --add channels markharfouche
conda config --show channels
```

```
# conda config --show channels
channels:
  - markharfouche
  - defaults
  - https://conda.anaconda.org/conda-forge
```

```
# conda config --show default_channels
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
```

**Comment by isuruf** [comment] 2020-08-03 16:46
Yes, that's a known (at least known to me) conda bug.

**Comment by ericpre** [comment] 2021-01-26 11:27
Should be fixed in https://github.com/conda/conda/pull/10479.

**Closed** 2021-03-29 23:43 UTC
