### ISSUE TITLE
Windows installer: option to add condabin in PATH

### ISSUE THREAD

**Issue by paugier** [conda-forge/miniforge#687] opened 2024-11-27 14:22 UTC
On Windows, it is not safe to add the main Miniforge script directory in PATH. However, the directory `C:\Users\myusername\miniforge3\condabin` should really be in PATH. There should be an option of the Windows installer to add it (and I even tend to think it should be enabled by default).

Without condabin in PATH, a workaround is to use Miniforge Prompt, but it is quite bad since in 2024 Windows users can and should use a better shell (PowerShell or Bash for example) and a better terminal ([Windows Terminal](https://aka.ms/terminal) for example).

The current solution is to add  `C:\Users\myusername\miniforge3\condabin` manually in PATH (mentioned in https://github.com/conda-forge/miniforge?tab=readme-ov-file#usage), but it's not so simple for many Windows users.

**Comment by hmaarrfk** [comment] 2024-12-11 15:04
Closing as duplicate of https://github.com/conda-forge/miniforge/issues/453

also see https://github.com/conda-forge/miniforge/issues/599 for why things move slow on windows.

I see you are helping answer a few questions. thank you!

**Closed by hmaarrfk** 2024-12-11 15:04 UTC
